spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/algafood?serverTimezone=UT
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    password: admin
    url: jdbc:mariadb://172.17.0.3:3306/algafood?serverTimezone=UTC
    username: root
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000

  resources.add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  jpa:
    show-sql: true
    #    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#logging:
#  level:
#    root: ERROR
algafood:
  storage:
    local:
      diretorio-fotos: "/home/jose/Desktop"