CREATE TABLE USUARIOS_RESTAURANTES_RESPONSAVEIS (
	USUARIOS_ID BIGINT NOT NULL,
	RESTAURANTES_ID BIGINT NOT NULL,
	PRIMARY KEY (USUARIOS_ID, RESTAURANTES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


ALTER TABLE USUARIOS_RESTAURANTES_RESPONSAVEIS ADD CONSTRAINT FK_USUARIOS_REST_RESPONSAVEIS_USUARIOS
FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS (ID);

ALTER TABLE USUARIOS_RESTAURANTES_RESPONSAVEIS ADD CONSTRAINT FK_USUARIOS_REST_RESPONSAVEIS_REST
FOREIGN KEY (RESTAURANTES_ID) REFERENCES RESTAURANTES (ID);