CREATE TABLE FOTOS_PRODUTOS (
	PRODUTOS_ID BIGINT NOT NULL,
	NOME VARCHAR(150),
	DESCRICAO VARCHAR(150),
	CONTENT_TYPE VARCHAR(80),
	TAMANHO INT,
	PRIMARY KEY (PRODUTOS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE FOTOS_PRODUTOS ADD CONSTRAINT FK_FOTO_PRODUTO_PRODUTO
FOREIGN KEY (PRODUTOS_ID) REFERENCES PRODUTOS (ID);